location:
  provider: ipstack
  ipstack:
    apiKey: ccccc9e33d375483db0b4b5b1262a328
    host: api.ipstack.com

weather:
  provider: weatherapi
  weatherapi:
    apiKey: 53f92237910c465dbb2193924210903
    host: api.weatherapi.com